language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
